
services:
  db:
    image: postgres:15
    container_name: shop_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always


  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: shop_web
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always

volumes:
  postgres_data: